### ISSUE TITLE
Broken hover in v4.7.0 release blog post

### ISSUE THREAD

**Issue by mhuisi** [leanprover/subverso#10]
![image](https://github.com/leanprover/subverso/assets/10852073/4622ea07-70c4-4d82-8475-f679a5fe6ea4)

**Comment by david-christiansen** [comment]
OK, it's fixed:
<img width="870" alt="Screenshot 2024-04-19 at 14 50 25" src="https://github.com/leanprover/subverso/assets/115330/e9573715-9a6e-4d92-adca-4f330949df37">
Thanks again!
